title: AmosX-沉一叶
description:   # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':year/:month/:day/:title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: 沉一叶 # add your name
author-img: amos.jpg # add your photo
about-author: 技术 | 随笔 # add description
motto: 一花一世界，一叶一菩提
motto1: 无处不有道
github: amos-hsu # add your Github handle
zhihu: WaterHsu
linkedin: # add your Linkedin handle
email: HuiyueHsu@gmail.com # add your Email address
address: Xi`an, China

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: Google Analytics

# Build Settings
markdown: kramdown
kramdown:
  input: GFM
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"
encoding: utf-8
highlight: true
highlighter: pygments
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "README.md"]
